"""add db

Revision ID: c5fce3ac61e0
Revises: 
Create Date: 2021-06-16 12:09:04.673426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5fce3ac61e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('admin', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'admin', 'roles', ['role_id'], ['id'])
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.drop_constraint(None, 'admin', type_='foreignkey')
    op.drop_column('admin', 'role_id')
    op.drop_table('roles')
    # ### end Alembic commands ###
